version: "3.9"

x-app:
  &app
  image: htr2hpc:${HTR2HPC_IMAGE_TAG:-latest}
  pull_policy: never
  volumes:
    - static:/usr/src/app/static
    - media:/usr/src/app/media
    - ssh:/usr/src/app/.ssh
  command: /bin/true
  environment:
    - DOMAIN
    - SECRET_KEY
    - CSRF_TRUSTED_ORIGINS
    - USE_X_FORWARDED_HOST
    - DEBUG
    - SITE_NAME
    - REDIS_HOST
    - REDIS_PORT
    - SQL_HOST
    - SQL_PORT
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    - DJANGO_SU_NAME
    - DJANGO_SU_EMAIL
    - DJANGO_SU_PASSWORD
    - DJANGO_FROM_EMAIL
    - DJANGO_SETTINGS_MODULE
    - FLOWER_BASIC_AUTH
    - EMAIL_HOST
    - SERVER_EMAIL
    - EMAIL_SUBJECT_PREFIX
    - ESCRIPTORIUM_HOST
    - HPC_HOSTNAME
    - HPC_SSH_KEYFILE
    - HPC_SSH_USER
    - HPC_WORKING_DIR
  networks:
    - escriptorium

services:

  web:
    <<: *app
    restart: always
    command: uwsgi --ini /usr/src/app/uwsgi.ini
    ports:
      - "8899:8899"

  channelserver:
    <<: *app
    restart: always
    command: daphne --bind 0.0.0.0 --port 5000 -v 1 escriptorium.asgi:application
    ports:
      - "5000:5000"

  db:
    image: docker.io/library/postgres:15
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - escriptorium

  redis:
    image: "docker.io/redis:alpine"
    restart: always
    networks:
      - escriptorium

  nginx:
    image: htr2hpc-nginx:${HTR2HPC_NGINX_IMAGE_TAG:-latest}
    pull_policy: never
    restart: always
    environment:
      - SERVERNAME=${DOMAIN:-localhost}
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    ports:
      - "0.0.0.0:8080:80"
    networks:
      - escriptorium

  celery-main:
    <<: *app
    restart: always
#    environment:
#      - OMP_NUM_THREADS=2
    command: "celery -A escriptorium worker -l INFO -E -Ofair --prefetch-multiplier 1 -Q default -c ${CELERY_MAIN_CONC:-10} --max-tasks-per-child=10"

  celery-live:
    <<: *app
    restart: always
    command: "celery -A escriptorium worker -l INFO -E -Ofair --prefetch-multiplier 1 -Q live -c ${CELERY_LIVE_CONC:-10} --max-tasks-per-child=10"

  celery-low-priority:
    <<: *app
    restart: always
    command: "celery -A escriptorium worker -l INFO -E -Ofair --prefetch-multiplier 1 -Q low-priority -c ${CELERY_LOW_CONC:-10} --max-tasks-per-child=10"

  celery-gpu: &celery-gpu
    <<: *app
    restart: always
    environment:
      - KRAKEN_TRAINING_DEVICE=cpu
    command: "celery -A escriptorium worker -l INFO -E -Ofair --prefetch-multiplier 1 -Q gpu -c 1 --max-tasks-per-child=1"

  flower:
    image: docker.io/mher/flower
    restart: always
    command: ["celery", "--broker=redis://redis:6379/0", "flower", "--port=5555"]
    ports:
      - 5555:5555
    networks:
      - escriptorium

  mail:
    image: registry.gitlab.com/scripta/escriptorium/mail
    environment:
      - PRIMARY_HOST=${DOMAIN:-localhost}
      - ALLOWED_HOSTS=web ; celery-main ; celery-low-priority; docker0
    networks:
      - escriptorium

volumes:
   static:
   media:
   postgres:
   esdata:
   ssh:

networks:
  escriptorium:
    name: escriptorium