[uwsgi]
# socket = 0.0.0.0:8899
# protocol = http
http = 0.0.0.0:8899

chdir = /usr/src/app/
module = escriptorium.wsgi:application

processes = 4

vacuum = True
master = true
respawn-on-exit = true
reload-on-rss = 1024 # Restart worker at 1 GB instead of waiting for OOM
max-requests = 1000  # Restart worker after N requests to prevent leaks
buffer-size = 32768

# Limit number of file descriptors to rein in memory used by uwsgi
# in docker on AlmaLinux 9.6; see:
# https://xahteiwi.eu/resources/hints-and-kinks/max-fd/
# https://github.com/sissbruecker/linkding/issues/946
max-df = 4096
