[uwsgi]
socket = 0.0.0.0:8899
protocol = http

chdir = /usr/src/app/
module = escriptorium.wsgi:application

processes = 4

vacuum = True
master = true
respawn-on-exit = true
reload-on-rss = 1024 # Restart worker at 1 GB instead of waiting for OOM
max-requests = 1000  # Restart worker after N requests to prevent leaks
buffer-size = 32768
